-- Jerarquia de servicios + destacados landing

create table if not exists public.service_groups (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  description text,
  image_url text,
  is_visible boolean not null default true,
  skip_subgroup_step_when_single_visible_child boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_subgroups (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.service_groups(id) on delete restrict,
  name text not null,
  slug text not null,
  description text,
  is_visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.service_groups enable row level security;
alter table public.service_subgroups enable row level security;

alter table public.servicios
  add column if not exists slug text,
  add column if not exists group_id bigint,
  add column if not exists subgroup_id bigint,
  add column if not exists sort_order integer not null default 0,
  add column if not exists landing_featured boolean not null default false,
  add column if not exists landing_sort_order integer,
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.servicios'::regclass
      and conname = 'servicios_group_id_fkey'
  ) then
    alter table public.servicios
      add constraint servicios_group_id_fkey
      foreign key (group_id) references public.service_groups(id) on delete restrict;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.servicios'::regclass
      and conname = 'servicios_subgroup_id_fkey'
  ) then
    alter table public.servicios
      add constraint servicios_subgroup_id_fkey
      foreign key (subgroup_id) references public.service_subgroups(id) on delete restrict;
  end if;
end$$;

create or replace function public.slugify_catalog_text(value text)
returns text
language sql
immutable
as $$
  select trim(both '-' from regexp_replace(
    lower(
      translate(
        coalesce(value, ''),
        'áàäâãåéèëêíìïîóòöôõúùüûñçÁÀÄÂÃÅÉÈËÊÍÌÏÎÓÒÖÔÕÚÙÜÛÑÇ',
        'aaaaaaeeeeiiiiooooouuuuncAAAAAAEEEEIIIIOOOOOUUUUNC'
      )
    ),
    '[^a-z0-9]+',
    '-',
    'g'
  ));
$$;

create or replace function public.current_service_group_mode(p_group_id bigint)
returns text
language sql
stable
as $$
  with has_direct as (
    select exists(
      select 1
      from public.servicios s
      where s.group_id = p_group_id
        and s.subgroup_id is null
    ) as value
  ),
  has_subgroups as (
    select exists(
      select 1
      from public.service_subgroups sg
      where sg.group_id = p_group_id
    ) as value
  )
  select case
    when (select value from has_direct) then 'services'
    when (select value from has_subgroups) then 'subgroups'
    else 'empty'
  end;
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.service_groups_before_write()
returns trigger
language plpgsql
as $$
declare
  v_slug text;
begin
  if new.name is null or btrim(new.name) = '' then
    raise exception 'Le nom du groupe est obligatoire';
  end if;

  if new.slug is null or btrim(new.slug) = '' then
    v_slug := public.slugify_catalog_text(new.name);
    if v_slug = '' then
      v_slug := 'groupe';
    end if;
    new.slug := v_slug;
  else
    new.slug := public.slugify_catalog_text(new.slug);
  end if;

  new.sort_order := coalesce(new.sort_order, 0);
  new.is_visible := coalesce(new.is_visible, true);
  new.skip_subgroup_step_when_single_visible_child := coalesce(new.skip_subgroup_step_when_single_visible_child, false);

  return new;
end;
$$;

create or replace function public.service_subgroups_before_write()
returns trigger
language plpgsql
as $$
declare
  v_slug text;
begin
  if new.name is null or btrim(new.name) = '' then
    raise exception 'Le nom du sous-groupe est obligatoire';
  end if;

  if new.group_id is null then
    raise exception 'Le groupe parent est obligatoire';
  end if;

  if public.current_service_group_mode(new.group_id) = 'services' then
    raise exception 'Ce groupe contient deja des services directs et ne peut pas recevoir de sous-groupes';
  end if;

  if new.slug is null or btrim(new.slug) = '' then
    v_slug := public.slugify_catalog_text(new.name);
    if v_slug = '' then
      v_slug := 'sous-groupe';
    end if;
    new.slug := v_slug;
  else
    new.slug := public.slugify_catalog_text(new.slug);
  end if;

  new.sort_order := coalesce(new.sort_order, 0);
  new.is_visible := coalesce(new.is_visible, true);

  return new;
end;
$$;

create or replace function public.servicios_before_write_hierarchy()
returns trigger
language plpgsql
as $$
declare
  v_slug text;
  v_subgroup_group_id bigint;
  v_existing_featured_count integer;
begin
  if new.nombre is null or btrim(new.nombre) = '' then
    raise exception 'Le nom du service est obligatoire';
  end if;

  if new.subgroup_id is not null then
    select group_id into v_subgroup_group_id
    from public.service_subgroups
    where id = new.subgroup_id;

    if v_subgroup_group_id is null then
      raise exception 'Le sous-groupe selectionne est introuvable';
    end if;

    new.group_id := v_subgroup_group_id;
  end if;

  if new.group_id is null then
    raise exception 'Le groupe parent est obligatoire';
  end if;

  if new.subgroup_id is null and public.current_service_group_mode(new.group_id) = 'subgroups' then
    raise exception 'Ce groupe contient deja des sous-groupes et ne peut pas recevoir de services directs';
  end if;

  if new.slug is null or btrim(new.slug) = '' then
    v_slug := public.slugify_catalog_text(new.nombre);
    if v_slug = '' then
      v_slug := 'service';
    end if;
    new.slug := v_slug;
  else
    new.slug := public.slugify_catalog_text(new.slug);
  end if;

  new.sort_order := coalesce(new.sort_order, 0);
  new.landing_featured := coalesce(new.landing_featured, false);

  if new.landing_featured then
    select count(*)::integer
      into v_existing_featured_count
    from public.servicios s
    where s.landing_featured = true
      and (tg_op = 'INSERT' or s.id <> new.id);

    if v_existing_featured_count >= 6 then
      raise exception 'Maximum 6 services mis en avant sur la landing';
    end if;
  end if;

  if not new.landing_featured then
    new.landing_sort_order := null;
  else
    new.landing_sort_order := coalesce(new.landing_sort_order, 0);
  end if;

  return new;
end;
$$;

drop trigger if exists trg_service_groups_before_write on public.service_groups;
create trigger trg_service_groups_before_write
before insert or update on public.service_groups
for each row execute function public.service_groups_before_write();

drop trigger if exists trg_service_groups_touch_updated_at on public.service_groups;
create trigger trg_service_groups_touch_updated_at
before update on public.service_groups
for each row execute function public.touch_updated_at();

drop trigger if exists trg_service_subgroups_before_write on public.service_subgroups;
create trigger trg_service_subgroups_before_write
before insert or update on public.service_subgroups
for each row execute function public.service_subgroups_before_write();

drop trigger if exists trg_service_subgroups_touch_updated_at on public.service_subgroups;
create trigger trg_service_subgroups_touch_updated_at
before update on public.service_subgroups
for each row execute function public.touch_updated_at();

drop trigger if exists trg_servicios_before_write_hierarchy on public.servicios;
create trigger trg_servicios_before_write_hierarchy
before insert or update on public.servicios
for each row execute function public.servicios_before_write_hierarchy();

drop trigger if exists trg_servicios_touch_updated_at on public.servicios;
create trigger trg_servicios_touch_updated_at
before update on public.servicios
for each row execute function public.touch_updated_at();

with inserted_group as (
  insert into public.service_groups (name, slug, description, is_visible, sort_order)
  select 'Services', 'services', 'Groupe initial cree automatiquement pendant la migration', true, 0
  where not exists (select 1 from public.service_groups)
  returning id
), ensured_group as (
  select id from inserted_group
  union all
  select id from public.service_groups order by id limit 1
)
insert into public.service_subgroups (group_id, name, slug, description, is_visible, sort_order)
select id, 'General', 'general', 'Sous-groupe initial cree automatiquement pendant la migration', true, 0
from ensured_group
where not exists (select 1 from public.service_subgroups);

with default_subgroup as (
  select sg.id, sg.group_id
  from public.service_subgroups sg
  order by sg.sort_order, sg.id
  limit 1
), ordered_services as (
  select id, row_number() over (order by id) - 1 as desired_order
  from public.servicios
)
update public.servicios s
set group_id = coalesce(s.group_id, ds.group_id),
    subgroup_id = coalesce(s.subgroup_id, ds.id),
    sort_order = os.desired_order,
    landing_featured = coalesce(s.landing_featured, false),
    updated_at = now()
from default_subgroup ds, ordered_services os
where os.id = s.id
  and (s.group_id is null
   or s.subgroup_id is null
   or s.sort_order is null);

with ordered_groups as (
  select id,
         public.slugify_catalog_text(name) as base_slug,
         row_number() over (partition by public.slugify_catalog_text(name) order by id) as dup_rank
  from public.service_groups
)
update public.service_groups g
set slug = case when og.dup_rank = 1 then og.base_slug else og.base_slug || '-' || og.dup_rank end
from ordered_groups og
where g.id = og.id
  and (g.slug is null or btrim(g.slug) = '');

with ordered_subgroups as (
  select id,
         public.slugify_catalog_text(name) as base_slug,
         row_number() over (partition by public.slugify_catalog_text(name) order by id) as dup_rank
  from public.service_subgroups
)
update public.service_subgroups sg
set slug = case when os.dup_rank = 1 then os.base_slug else os.base_slug || '-' || os.dup_rank end
from ordered_subgroups os
where sg.id = os.id
  and (sg.slug is null or btrim(sg.slug) = '');

with ordered_services as (
  select id,
         public.slugify_catalog_text(nombre) as base_slug,
         row_number() over (partition by public.slugify_catalog_text(nombre) order by id) as dup_rank
  from public.servicios
)
update public.servicios s
set slug = case when os.dup_rank = 1 then os.base_slug else os.base_slug || '-' || os.dup_rank end,
    landing_featured = coalesce(s.landing_featured, false),
    updated_at = now()
from ordered_services os
where s.id = os.id
  and (s.slug is null or btrim(s.slug) = '');

update public.service_groups set sort_order = coalesce(sort_order, 0);
update public.service_subgroups set sort_order = coalesce(sort_order, 0);
update public.servicios set sort_order = coalesce(sort_order, 0), landing_featured = coalesce(landing_featured, false);

alter table public.servicios
  alter column slug set not null,
  alter column group_id set not null,
  alter column landing_featured set not null,
  alter column sort_order set not null;

create unique index if not exists service_groups_slug_key_idx
  on public.service_groups (slug);
create unique index if not exists service_subgroups_slug_key_idx
  on public.service_subgroups (slug);
create unique index if not exists servicios_slug_key_idx
  on public.servicios (slug);

create unique index if not exists service_groups_name_unique_idx
  on public.service_groups (lower(name));
create unique index if not exists service_subgroups_group_name_unique_idx
  on public.service_subgroups (group_id, lower(name));
create unique index if not exists servicios_direct_group_name_unique_idx
  on public.servicios (group_id, lower(nombre))
  where subgroup_id is null;
create unique index if not exists servicios_subgroup_name_unique_idx
  on public.servicios (subgroup_id, lower(nombre))
  where subgroup_id is not null;

create index if not exists service_groups_sort_order_idx on public.service_groups (sort_order, id);
create index if not exists service_subgroups_group_sort_order_idx on public.service_subgroups (group_id, sort_order, id);
create index if not exists servicios_group_sort_order_idx on public.servicios (group_id, subgroup_id, sort_order, id);
create index if not exists servicios_landing_featured_sort_idx on public.servicios (landing_featured, landing_sort_order, sort_order, id);

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='service_groups' and policyname='service_groups_public_read'
  ) then
    create policy service_groups_public_read on public.service_groups
      for select to public
      using (true);
  end if;
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='service_groups' and policyname='service_groups_admin_insert'
  ) then
    create policy service_groups_admin_insert on public.service_groups
      for insert to authenticated
      with check (public.current_user_role() = 'admin');
  end if;
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='service_groups' and policyname='service_groups_admin_update'
  ) then
    create policy service_groups_admin_update on public.service_groups
      for update to authenticated
      using (public.current_user_role() = 'admin')
      with check (public.current_user_role() = 'admin');
  end if;
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='service_groups' and policyname='service_groups_admin_delete'
  ) then
    create policy service_groups_admin_delete on public.service_groups
      for delete to authenticated
      using (public.current_user_role() = 'admin');
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='service_subgroups' and policyname='service_subgroups_public_read'
  ) then
    create policy service_subgroups_public_read on public.service_subgroups
      for select to public
      using (true);
  end if;
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='service_subgroups' and policyname='service_subgroups_admin_insert'
  ) then
    create policy service_subgroups_admin_insert on public.service_subgroups
      for insert to authenticated
      with check (public.current_user_role() = 'admin');
  end if;
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='service_subgroups' and policyname='service_subgroups_admin_update'
  ) then
    create policy service_subgroups_admin_update on public.service_subgroups
      for update to authenticated
      using (public.current_user_role() = 'admin')
      with check (public.current_user_role() = 'admin');
  end if;
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='service_subgroups' and policyname='service_subgroups_admin_delete'
  ) then
    create policy service_subgroups_admin_delete on public.service_subgroups
      for delete to authenticated
      using (public.current_user_role() = 'admin');
  end if;
end$$;
